# Grouping Numbers In A List

This solution uses the numpy library. The program creates a sequential array of numbers using a specified length, shuffles that array, and splits them into sub-arrays that are of equal size. If the array cannot be equally split, then one sub-array will be shorter than the rest.

In [4]:
import numpy as np

def random_assignment(num_students, num_groups):
    arr = np.arange(num_students)
    np.random.shuffle(arr)
    return np.array_split(arr, num_groups)

num_students = 19
groups = 4

random_assignment(num_students, groups)

[array([17, 16, 12, 13, 11]),
 array([0, 3, 5, 9, 4]),
 array([10,  8,  2,  7,  6]),
 array([18,  1, 14, 15])]